import trimesh
import os

def convert_obj_to_stl(obj_path: str, output_stl_path: str) -> str:
    """
    Converts a .obj or .glb file generated by the AI model into a 3D printable .stl file.
    """
    if not os.path.exists(obj_path):
        raise FileNotFoundError(f"Source file not found at {obj_path}")
        
    # Load the mesh using trimesh
    mesh = trimesh.load(obj_path)
    
    # Export as STL
    mesh.export(output_stl_path)
    return output_stl_path 

def save_mesh_from_bytes(mesh_bytes, output_path):
    """Temporary placeholder to prevent import errors"""
    with open(output_path, "wb") as f:
        f.write(mesh_bytes)
    return output_path 